routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/view/{id}', 'HomeController@jobView')->name('view');
Route::get('/categories', 'HomeController@jobCategories')->name('jobs-categories');
Route::get('/categories/{id}', 'HomeController@allJobsByCategory')->name('jobs-categories-id');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('autocomplete',array('as'=>'autocomplete','uses'=>'HomeController@autocomplete'));
Route::get('/job/search','HomeController@searchComplete')->name('jobs.search');

Route::get('/user/logout', 'auth\LoginController@userlogout')->name('user.logout');


// Route::get('/home', 'HomeController@index')->name('home');
Route::prefix('thegate')->namespace('Admin')->group(function(){
	//Dashboard=====================================
	Route::get('/','DashboardController@index')->name('thegate.dashboard');
	//Admin Login-Logout=========================
	Route::get('/login','LoginController@show')->name('thegate.login');
	Route::post('/login','LoginController@login')->name('thegate.login.submit');
	Route::get('/logout', 'LoginController@logout')->name('thegate.logout');

	//Job_Categories==============================
	Route::get('job_categories','JobCategoriesController@index')->name('job_categories.index');
	Route::get('job_categories/create','JobCategoriesController@create')->name('job_categories.create');
	Route::post('job_categories','JobCategoriesController@store')->name('job_categories.submit');
	Route::get('job_categories/{id}','JobCategoriesController@edit')->name('job_categories.edit');
	Route::post('job_categories/update/{id}','JobCategoriesController@update')->name('job_categories.update');
	Route::post('job_categories/delete','JobCategoriesController@delete')->name('job_categories.delete');

	//Job Location===============================
	Route::get('job_location','JobLocationsController@index')->name('job_location.index');
	Route::get('job_location/create','JobLocationsController@create')->name('job_location.create');
	Route::post('job_location','JobLocationsController@store')->name('job_location.submit');
	Route::get('job_location/{id}','JobLocationsController@edit')->name('job_location.edit');
	Route::post('job_location/update/{id}','JobLocationsController@update')->name('job_location.update');
	Route::post('job_location/delete','JobLocationsController@delete')->name('job_location.delete');


	//Job Schedule===============================
	Route::get('job_schedule','JobScheduleController@index')->name('job_schedule.index');
	Route::get('job_schedule/create','JobScheduleController@create')->name('job_schedule.create');
	Route::post('job_schedule','JobScheduleController@store')->name('job_schedule.submit');
	Route::get('job_schedule/{id}','JobScheduleController@edit')->name('job_schedule.edit');
	Route::post('job_schedule/update/{id}','JobScheduleController@update')->name('job_schedule.update');
	Route::post('job_schedule/delete','JobScheduleController@delete')->name('job_schedule.delete');

	//Job Company===============================
	Route::get('companies','CompanyController@index')->name('companies.index');
	Route::get('companies/create','CompanyController@create')->name('companies.create');
	Route::post('companies','CompanyController@store')->name('companies.submit');
	Route::get('companies/{id}','CompanyController@edit')->name('companies.edit');
	Route::post('companies/update/{id}','CompanyController@update')->name('companies.update');
	Route::post('companies/delete','CompanyController@delete')->name('companies.delete');
	Route::post('companies/approved/{id}','CompanyController@approved')->name('comapnies.approved');


	//Job Post===============================
	Route::get('post_job/admin','PostJobController@admin')->name('post_job.admin.index');
	Route::get('post_job/client','PostJobController@client')->name('post_job.client.index');
	Route::get('post_job/create','PostJobController@create')->name('post_job.create');
	Route::post('post_job','PostJobController@store')->name('post_job.submit');
	Route::get('post_job/{id}','PostJobController@edit')->name('post_job.edit');
	Route::post('post_job/update/{id}','PostJobController@update')->name('post_job.update');
	Route::post('post_job/delete','PostJobController@delete')->name('post_job.delete');

	Route::post('post_job/job/{id}','PostJobController@approve')->name('post_job.approve');

	//User cliden====================================
	Route::get('user/client','UserClientController@index')->name('user.client.index');
	Route::post('user/client/delete','UserClientController@delete')->name('user.client.delete');
	Route::post('user/client/type/client','UserClientController@client')->name('user.client.update.client');
	Route::post('user/client/type/admin','UserClientController@admin')->name('user.client.update.admin');
	//Order=========================
	



	// Management=====================================
	Route::get('user/admin','UserAdminController@index')->name('user.admin');
	Route::get('user/admin/create','UserAdminController@create')->name('user.admin.create');
	Route::post('user/admin/create','UserAdminController@store')->name('user.admin.create.submit');
	Route::get('user/admin/edit/{id}','UserAdminController@edit')->name('user.admin.edit');
	Route::post('user/admin/update/{id}','UserAdminController@update')->name('user.admin.update');
	Route::post('user/admin/delete','UserAdminController@delete')->name('user.admin.delete');

});



//user Dashbaord client
Route::prefix('user')->name('user.')->group(function () {
    Route::get('/', ['as' => 'index', 'uses' => 'UserDashboardController@index']); 
});
Route::prefix('user')->group(function () {

	//Companies================================================
	Route::get('companies','UserCompanyController@index')->name('user.company'); 
	Route::get('companies/create', 'UserCompanyController@create')->name('user.create.company');
	Route::post('companies/post', 'UserCompanyController@store')->name('user.submit.company'); 
	Route::get('companies/edit/{id}', 'UserCompanyController@edit')->name('user.edit.company'); 
	Route::post('companies/update/{id}','UserCompanyController@update')->name('user.update.company');
	Route::post('companies/delete','UserCompanyController@delete')->name('user.delete.company');

	//Job ===============================================================================	
	Route::post('job/delete','UserJobsController@delete')->name('user.job.delete');

	//CV=============================
	Route::get('job/applied','ApplyJobController@getapply')->name('user.apply.job.index');
	Route::get('view/cv/{id}','ApplyJobController@viewcv')->name('view.cv');
	Route::post('view/cv/delete','ApplyJobController@delete')->name('view.cv.deletes');




	
	
});
Route::prefix('user/jobs')->name('user.')->group(function () {
	Route::get('/', ['as' => 'job.index', 'uses' => 'UserJobsController@index']); 
	Route::get('/create', ['as' => 'job.create', 'uses' => 'UserJobsController@create']); 
	Route::post('/store', ['as' => 'job.store', 'uses' => 'UserJobsController@store']); 
	Route::get('/edit/{id}', ['as' => 'job.edit', 'uses' => 'UserJobsController@edit']); 
	Route::post('/update/{id}', ['as' => 'job.update', 'uses' => 'UserJobsController@update']); 

	
});

//Apply Job==============================================
Route::get('apply/job/{id}','ApplyJobController@apply')->name('user.cleint.apply.job');
Route::post('apply/job/submit','ApplyJobController@applysubmit')->name('user.clent.apply.job.submit');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/front/user/jobs/create.blade.php
@extends('layouts.app')
@section('content')
<br>


<div class="col-md-12 mb-5 mb-md-0">

  <div class="card">
    <div class="card-header">Create Job</div>
    <div class="card-body">
      <form action="{{route('user.job.store')}}" method="post">
        @csrf

        <div class="row">
          <div class="col-md-6">

            
        <div class="form-group {{ $errors->has('title') ? 'has-error' : ''}}">
          <label for="">Job Title</label>
          <input type="text" class="form-control" placeholder="Enter Job Title" name="title" value="{{old('title')}}">
          @if($errors->has('title'))
          <span class="has-error">
            {{ $errors->first('title') }}
          </span>
          @endif
        </div>
        <div class="form-group {{ $errors->has('company') ? 'has-error' : ''}}">
          <label for="">Select Company</label>
          <select type="text" name="company" class="form-control">
            @foreach ($companies as $com)
            <option value="{{$com->id}}">{{$com->company_name}}</option>
            @endforeach
          </select>
          @if($errors->has('company'))
          <span class="has-error">
            {{ $errors->first('company') }}
          </span>
          @endif
        </div>
        
        <div class="form-group {{ $errors->has('category') ? 'has-error' : ''}}">
          <label for="">Select Categories</label>
          <select type="text" class="form-control" name="category">
            @foreach ($categories as $com)
            <option value="{{$com->id}}">{{$com->jobcategoriesname}}</option>
            @endforeach
          </select>
          @if($errors->has('category'))
          <span class="has-error">
            {{ $errors->first('category') }}
          </span>
          @endif
        </div>
        <div class="form-group {{ $errors->has('location') ? 'has-error' : ''}}">
          <label for="">Select Locaiton</label>
          <select type="text" class="form-control" name="location" >
            @foreach ($locations as $com)
            <option value="{{$com->id}}">{{$com->joblocation}}</option>
            @endforeach
          </select>
          @if($errors->has('location'))
          <span class="has-error">
            {{ $errors->first('location') }}
          </span>
          @endif
        </div>

          </div>
          <div class="col-md-6 {{ $errors->has('schedule') ? 'has-error' : ''}}">
            <div class="form-group">
              <label for="">Select Schedule</label>
              <select type="text" class="form-control" name="schedule">
                @foreach ($schedules as $com)
                <option value="{{$com->id}}">{{$com->schedule_name}}</option>
                @endforeach
              </select>
              @if($errors->has('schedule'))
              <span class="has-error">
                {{ $errors->first('schedule') }}
              </span>
              @endif
            </div>
            <div class="form-group {{ $errors->has('salary') ? 'has-error' : ''}}">
              <label for="">Salary $ </label>
              <input type="number" name="salary" class="form-control" placeholder="200.00 $" value="0">
              @if($errors->has('salary'))
              <span class="has-error">
                {{ $errors->first('salary') }}
              </span>
              @endif
            </div>

            <div class="form-group {{ $errors->has('close_date') ? 'has-error' : ''}}">
              <label for="">Dateline</label>
              <input type="text" class="form-control" id="txtdate" name="close_date" placeholder="Please Dateline...">
                @if($errors->has('close_date'))
                <span class="has-error">
                  {{ $errors->first('close_date') }}
                </span>
                @endif
            </div>

            
          </div>
         
          
        </div>

        <div class="form-group {{ $errors->has('duties') ? 'has-error' : ''}}">
          <label for="">Duties</label>
          <textarea name="duties" class="form-control" id="" cols="30" rows="5">{{old('duties')}}</textarea>
          @if($errors->has('duties'))
          <span class="has-error">
            {{ $errors->first('duties') }}
          </span>
          @endif
        </div>
        <div class="form-group {{ $errors->has('requirements') ? 'has-error' : ''}}">
          <label for="">Requirements</label>
        <textarea name="requirements" class="form-control" id="" cols="30" rows="5" >{{old('requirements')}}</textarea>
          @if($errors->has('requirements'))
          <span class="has-error">
            {{ $errors->first('requirements') }}
          </span>
          @endif
        </div>


        <div class="form-group">
          <input type="submit" value="Post a Job" class="btn btn-primary float-right" >
        </div>
      </form>

    </div>
    
  </div>



</div>

<br>
<br>

@endsection

resources/views/front/user/jobs/edit.blade.php
@extends('layouts.app')
@section('content')
<br>


<div class="col-md-12 mb-5 mb-md-0">

  <div class="card">
    <div class="card-header"><h4>
      Edit Job
      <a href="{{route('user.company')}}" class="btn btn-primary float-right">Back</a>
    </h4></div>
    <div class="card-body">
      <form action="{{route('user.job.update',['id'=>$job->id])}}" method="post">
        @csrf

        <div class="row">
          <div class="col-md-6">

            <div class="form-group">
              <label for="">Job Title</label>
              <input type="text" class="form-control" placeholder="Enter Job Title" name="title" required value="{{$job->job_title}}">
              @if($errors->has('title'))
              <span class="has-error">
                {{ $errors->first('title') }}
              </span>
              @endif
            </div>

           <div class="form-group">
            <label for="">Select Company</label>
            <select type="text" name="company" class="form-control">
              @foreach ($companies as $com)
              {{-- <option value="{{$val->id}}" {{$postjob->category_id == $val->id  ? 'selected' : ''}}>{{$val->jobcategoriesname}}</option> --}}
  
                <option value="{{$com->id}} "  {{$job->company_id == $com->id  ? 'selected' : ''}}>{{$com->company_name}}</option>
              @endforeach
            </select>
            @if($errors->has('company'))
            <span class="has-error">
              {{ $errors->first('company') }}
            </span>
            @endif
          </div>
          <div class="form-group">
            <label for="">Select Categories</label>
            <select type="text" class="form-control" name="category">
              @foreach ($categories as $com)
              <option value="{{$com->id}}" {{$job->category_id == $com->id  ? 'selected' : ''}} >{{$com->jobcategoriesname}}</option>
              @endforeach
            </select>
            @if($errors->has('category'))
            <span class="has-error">
              {{ $errors->first('category') }}
            </span>
            @endif
          </div>
          <div class="form-group">
            <label for="">Select Locaiton</label>
            <select type="text" class="form-control" name="location" >
              @foreach ($locations as $com)
              <option value="{{$com->id}}" {{$job->location_id == $com->id  ? 'selected' : ''}}>{{$com->joblocation}}</option>
              @endforeach
            </select>
            @if($errors->has('location'))
            <span class="has-error">
              {{ $errors->first('location') }}
            </span>
            @endif
          </div>
 
        

          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="">Select Schedule</label>
              <select type="text" class="form-control" name="schedule">
                @foreach ($schedules as $com)
                <option value="{{$com->id}}" {{$job->schedule_id == $com->id  ? 'selected' : ''}}>{{$com->schedule_name}}</option>
                @endforeach
              </select>
              @if($errors->has('schedule'))
              <span class="has-error">
                {{ $errors->first('schedule') }}
              </span>
              @endif
            </div> 


            <div class="form-group">
              <label for="">Salary $ </label>
            <input type="number" value="{{floatval($job->salary)}}" name="salary" class="form-control" placeholder="200.00 $" value="0" required>
              @if($errors->has('salary'))
              <span class="has-error">
                {{ $errors->first('salary') }}
              </span>
              @endif
            </div>
            <div class="form-group">
              <label for="">Dateline</label>
            <input value="{{$job->close_date}}" type="text" class="form-control" id="txtdate" name="close_date" placeholder="Please Dateline..."
                required>
                @if($errors->has('close_date'))
                <span class="has-error">
                  {{ $errors->first('close_date') }}
                </span>
                @endif
            </div>

            
          </div>
         
          
        </div>

        <div class="form-group">
          <label for="">Duties</label>
          <textarea  name="duties" class="form-control" id="" cols="30" rows="5" required >
            {{$job->duties}}
          </textarea>
          @if($errors->has('duties'))
          <span class="has-error">
            {{ $errors->first('duties') }}
          </span>
          @endif
        </div>
        <div class="form-group">
          <label for="">Requirements</label>
          <textarea name="requirements" class="form-control" id="" cols="30" rows="5" required>
            {{$job->requirements}}
          </textarea>
          @if($errors->has('requirements'))
          <span class="has-error">
            {{ $errors->first('requirements') }}
          </span>
          @endif
        </div>


        <div class="form-group">
          <input type="submit" value="Update Job" class="btn btn-primary float-right" >
        </div>
      </form>

    </div>
    
  </div>



</div>

<br>

@endsection

resources/views/front/user/jobs/index.blade.php
@extends('layouts.app')
@section('content')
<br>

<div class="col-md-12 mb-5 mb-md-0">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                All Jobs
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-hover">
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Job Title</th>
                    <th>Company</th>
                    <th>Location</th>
                    <th>Close Date</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
    
                  @foreach($jobs as $val)
                  <tr>
                    <th>{{$val->id}}</th>
                    <td>{{$val->job_title}}</td>
                    <td>{{$val->company_name}}</td>
                    <td>
                      {{$val->joblocation}}
                    </td>
                    <td>{{$val->close_date}}</td>
                    <td>
                   
                          
                  <a href="{{route('user.job.edit',$val->id)}}" class="btn btn-primary btn-sm" >
                        <i class="glyphicon glyphicon-pencil">Edit</i>
                      </a>
  
                      <a href="" class="btnDelteCom btn btn-danger btn-sm" data-id="{{$val->id}}">
                            <i class="glyphicon glyphicon-trash">Delete</i>
                        </a>
                    </td>
                 @endforeach
                </tbody>
              </table>
              <div class="pull-right">
                {{$jobs->links()}}
              </div>
        </div>
    </div>
</div>
<br>

<script>
  $(document).ready(function(){

    $(".btnDelteCom").click(function(e) {

      e.preventDefault();
        var id = $(this).data('id');
          Swal.fire({
            title: 'Are you sure to delete ?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
          }).then((result) => {
              if (result.value) {
              $.ajax({
              type: 'post',
              url: "{{route('user.job.delete')}}",
              data: {'_token':'{{ csrf_token() }}','id':id},
              success: function(response)
              {
                  location.reload();
              }
        });
        }
      })
    });
  });
</script>

@endsection